import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useForm } from "react-hook-form";
import useAuth from "../../hooks/useAuth";

function Login() {
  const [login, setLogin] = useState(false);
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();
  const { singIn, singUp } = useAuth();
  const onSubmit = async ({ email, password }) => {
    if (login) {
      await singIn(email, password);
    } else {
      await singUp(email, password);
    }
  };
  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src="https://rb.gy/p2hphi"
        layout="fill"
        className="login--poster"
      />
      <img
        src="https://rb.gy/ulxxee"
        className="logo"
        width={150}
        height={150}
      />

      <div className="form form-container">
        <form className="form-control" onSubmit={handleSubmit(onSubmit)}>
          <h1 className="form-header">Sing In</h1>
          <div>
            <label htmlFor="">
              <input
                type="email"
                placeholder="Email"
                className="form-input"
                {...register("email", { required: true })}
              />
              {errors.email && <span>Enter Valid Email</span>}
            </label>
            <label htmlFor="">
              <input
                type="password"
                placeholder="PassWord"
                className="form-input"
                {...register("password", { required: true })}
              />
              {errors.password && <span>password is required</span>}
            </label>
          </div>
          <button
            className="btn btn-singin"
            type="submit"
            onClick={() => setLogin(true)}>
            Sing In
          </button>
          <div className="text">
            <span>New to Netflix? </span>
            <button className="btn btn-singup" onClick={() => setLogin(false)}>
              Sing Up now
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default Login;
