import Head from "next/head";
import Header from "./components/Header";

const Home = () => {
  return (
    <>
      <Head>
        <title>home - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />       
      </Head>
      <main>
        <Header />
      </main>
    </>
  );
};

export default Home;
