import Head from "next/head";
import requests from "../utils/request";
import Benner from "./components/Benner";
import Header from "./components/Header";
import RowsList from "./components/RowsList";

const Home = (props) => {
  const {
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentaries,
  } = props;
  return (
    <div className="container">
      <Head>
        <title>home - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Benner netflixOriginals={netflixOriginals} />
        <section>
          <RowsList title="Trending Now" movies={trendingNow} />
          <RowsList title="Top Rated" movies={topRated} />
          <RowsList title="Action Thrillers" movies={actionMovies} />
          {/* My List */}
          {/* {list.length > 0 && <RowsList title="My List" movies={list} />} */}

          <RowsList title="Comedies" movies={comedyMovies} />
          <RowsList title="Scary Movies" movies={horrorMovies} />
          <RowsList title="Romance Movies" movies={romanceMovies} />
          <RowsList title="Documentaries" movies={documentaries} />
        </section>
      </main>
    </div>
  );
};

export const getServerSideProps = async (props) => {
  const [
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentaries,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
    fetch(requests.fetchTrending).then((res) => res.json()),
    fetch(requests.fetchTopRated).then((res) => res.json()),
    fetch(requests.fetchActionMovies).then((res) => res.json()),
    fetch(requests.fetchComedyMovies).then((res) => res.json()),
    fetch(requests.fetchHorrorMovies).then((res) => res.json()),
    fetch(requests.fetchRomanceMovies).then((res) => res.json()),
    fetch(requests.fetchDocumentaries).then((res) => res.json()),
  ]);

  return {
    props: {
      netflixOriginals: netflixOriginals.results,
      trendingNow: trendingNow.results,
      topRated: topRated.results,
      actionMovies: actionMovies.results,
      comedyMovies: comedyMovies.results,
      horrorMovies: horrorMovies.results,
      romanceMovies: romanceMovies.results,
      documentaries: documentaries.results,
    },
  };
};
export default Home;
